# Generated by Django 6.0.3 on 2026-04-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CUSTOM USER MODEL', 'User Model'), ('ROLE HIERARCHY ENFORCEMENT', 'Role Hierarchy Enforcement'), ('USER CREATION & MODIFICATION', 'User Creation & Modification'), ('CUSTOMER ONBOARDING', 'Customer Onboarding'), ('AUDIT LOGGING READY', 'Audit Logging Ready')], max_length=30, unique=True)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('HIERARCHICAL PERMISSION CONTROL', 'Hierarchical Permission'), ('RESTRICTED ACCESS LEVELS', 'Restricted Access'), ('API-BASED DESIGN', 'API-Based Design')], max_length=60, unique=True)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SUPERADMIN CREATES GENERAL MANAGER', 'General Manager'), ('GENERAL MANAGER CREATE OPERATIONS MANAGER', 'Operations Manager'), ('OPERATIONS MANAGER CREATE DEPARTMENT HEAD/SALES MANAGER', 'Department Head/Sales Manager'), ('SALES MANAGER CREATE TELECALLERS', 'Telecallers'), ('TELECALLERS CREATE CUSTOMERS', 'Customers'), ('UNDERWRITER HANDLES APPROVALS', 'Underwriter'), ('ACCOUNTS MANAGES FINANCIAL ACTIONS', 'Accounts')], max_length=60, unique=True)),
                ('level', models.IntegerField()),
            ],
        ),
    ]
